### ISSUE TITLE
Error packages

### ISSUE THREAD

**Issue by MarioZavala2000123** [apetrynet/pyfilemail#9]
I have problems in the code, when I do "pip install pyfilemal" it shows me an error in the packages.
Collecting pyfilemail
  Using cached pyfilemail-0.5.1.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pczt\AppData\Local\Temp\pip-install-a166mp1v\pyfilemail_fdc68871946947bbae7d60c2a2071c9d\setup.py", line 4, in <module>
          import pyfilemail
        File "C:\Users\pczt\AppData\Local\Temp\pip-install-a166mp1v\pyfilemail_fdc68871946947bbae7d60c2a2071c9d\pyfilemail\__init__.py", line 112
          """
             ^
      SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 162-163: truncated \UXXXXXXXX escape
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MarioZavala2000123** [comment]
Thank you very much, but I download the CLI and it only opens a command window for **seconds and closes**, what can I do?
Also, can I use **pyfilemail** if I install python 2?

**Comment by apetrynet** [comment]
Please note I don't have a windows machine myself and don't work for Filemail, so this is from memory.

Did you "double click" a Filemail.exe icon? If so, it might have launched a command window and closed it again since it didn't get all the required arguments.
Please try to open a command window (windows-button+r and and enter `cmd.exe`) and browse to the folder where you saved the Filemail.exe file. (`cd C:\some\path` ) Then launch enter `Filemail.exe --help` for instructions. You might need to install a dependency mentioned in the [documentation](https://www.filemail.com/apidoc/FilemailLibs.aspx).

I can't guarantee it will work with Python2, but it might be worth a shot. The code is quite old, so a lot might have changed. 

If you wrap the CLI in a subprocess you should consider adding the full path to the folder containing the `Filemail.exe` file to the `PATH` environment variable. I think this is done in the window you get if you right click MyMachine->properties.
If you don't add it to `PATH`  you ned to pass the full path in the subprocess.

Good luck! Hope you figure it out :)

**Comment by MarioZavala2000123** [comment]
thanks a lot my friend!
